### PR TITLE
rebar doesn't respect the order of erl_first_files given in the rebar.conf file

### PR DESCRIPTION
**Pull request by norton**
The first commit is a fix for this issue.  The second commit is a test for this issue.  The second commit will fail if cherry-picked to the current master branch.

### CODE REVIEW

**Comment by norton** [comment]
This merge request is for issue #429.

**Comment by ferd** [comment]
So just so I'm clear, was the issue that `lists:partition` does not keep the expected order of files?

**Comment by norton** [comment]
No.  The root issue is that AllErlFiles is not sorted to respect the order of ErlFirstFiles.

**Comment by tuncer** [comment]
> The root issue is that AllErlFiles is not sorted to respect the order of ErlFirstFiles.

So, should we sort in `gather_src/2`, then?

**Comment by norton** [comment]
I don't think so.  The fix made by Slava is fine by me.

**Comment by nevar** [comment]
After we make `lists:partition` we loose order in `ErlFirstFilesConf`. We use order from file system and that is where bug came. We loose dependency order from user defined order.

**Comment by ferd** [comment]
Ok, that makes sense to me. @tuncer anything else you can think of before I merge this in later today?

**Comment by tuncer** [comment]
We can merge this, and I had a quick chat with @nevar that may or may not result in a follow-up ticket.

**Comment by tuncer** [comment]
We can merge it as a fix, even though I don't like the extra list traversals too much.

**Comment by norton** [comment]
Just checking ... Is anything else required for this pull request?

**Comment by nevar** [comment]
@norton If you complete remove erl_first_files from config does rebar compile file in right order?

My main issue with this that erl_first_files use as is and don't order by rebar inner [algorithm](https://github.com/rebar/rebar/blob/master/src/rebar_erlc_compiler.erl#L320). So we need remove don't exists file and hope that user use correct order for this file.

I think that better ignore erl_first_files and use rebar algorithm for order files. But I not sure that all use case didn't use erl_first_files for some interesting behavior or rebar correct parse and analyze all posible erl file.

We can deprecate erl_first_files and lay on rebar order algorithm and improve it. Or keep erl_first_files and have more and more code for that options.

So my main question: Why we need erl_first_files if rebar can order erl file by himself?

**Comment by norton** [comment]
@nevar fixing the behavior of erl_first_files and deprecating el_first_files are different goals.  My goal for this issue is simply to fix the erl_first_files regression reported in #429 and not introduce any new harm.

**Comment by tuncer** [comment]
I've been thinking of ways to avoid the extra scanning, and didn't come up with a good solution. In order to fix the issue, we should get this in and try to optimize it in another patch.

**Comment by tuncer** [comment]
To deprecate or remove `erl_first_files`, we'd have to be sure there are no valid cases where `erl_first_files` is used for something not covered by dependency resolution.

**Comment by norton** [comment]
+1

**Comment by norton** [comment]
+1

**Pull request merged**
