### PR TITLE
Exit with proper status code if 'eval' fails

### PR DESCRIPTION
**Pull request by robertoaloi**

### CODE REVIEW

**Comment by tuncer** [comment]
Seems reasonable. Would it make sense to extract this into a helper function in the script?

**Comment by tuncer** [comment]
Seems reasonable. Would it make sense to extract this into a helper function in and update the whole script?

**Comment by ferd** [comment]
This change makes sense. Where else would you see it, @tuncer ?

I believe this also needs to be rebased on master so tests pass.

**Comment by tuncer** [comment]
I was suggesting that we might use the opportunity to make it a shell function and reuse everywhere $? is checked.

**Comment by robertoaloi** [comment]
@ferd Rebased on latest master.
@tuncer I agree some refactoring would be nice for the script, but I would consider that a separate issue from this one.

**Comment by tuncer** [comment]
> but I would consider that a separate issue from this one

Works for me.

**Pull request merged**
