### PR TITLE
Don't crash if missing OTP_VERSION file (fix #350)

### LINKED ISSUE #350: Rebar 2.5.1 crashes with a reltool-generated release on Erlang 17+
It seems that with a reltool generated release, rebar will crash when checking the OTP version due to the version change.  Version 2.5.0 works okay (the commit that breaks it is this: https://github.com/rebar/rebar/commit/873d236ce9b4b88d46c4bb1c6868df70363e8a57)

It crashes on this line: https://github.com/rebar/rebar/blob/master/src/rebar_utils.erl#L391 because the generated release doesn't include the OTP_VERSION file in the releases directory by default.

I'm unsure if this is something that should be fixed within rebar or if it's an oversight by the otp team with the release of Erlang 17, but I thought I'd mention it here.

The full error is as follows:
```erlang
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,enoent}},
                                [{rebar_utils,otp_release1,1,
                                  [{file,"src/rebar_utils.erl"},{line,391}]},
                                 {rebar_utils,get_arch,0,
                                  [{file,"src/rebar_utils.erl"},{line,92}]},
                                 {rebar_port_compiler,default_env,0,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,574}]},
                                 {rebar_port_compiler,setup_env,2,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,181}]},
                                 {rebar_core,'-setup_envs/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,522}]},
                                 {lists,foldl,3,
                                  [{file,"lists.erl"},{line,1261}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,293}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,258}]}]}}
make[3]: *** [get-deps] Error 1
```

I haven't spent any time looking at this too closely to try and fix it yet, I just reverted to 2.5.0 because it works well enough.

Thanks!

### PR DESCRIPTION
**Pull request by choptastic**
This is a simpler version of the fix presented in #501. If generates a WARN if no OTP_VERSION file is found, and resorts to the return of erlang:system_info(otp_release).

I wrapped the otp_release1 function in a simple process dictionary cache to prevent it from being called many times (in my tests it's called quite frequently - like a few hundred times, and since for OTP 17+, there's a hard drive or two for each call, I figured caching the result might speed things up a bit).

Anyway, let me know what you think.

### CODE REVIEW

**Comment by tuncer** [comment]
+1, even though I'm not sure about the use of pdict here. However, in this special case, like for rebar_log settings, it seems okay to use the process dictionary instead of putting it into rebar_config:config(). Let's get this into 2.6.0, once the minor issues are fixed.

**Comment by choptastic** [comment]
Thanks, wow that was quite the abundance of typos. Yesterday must not have been a great day for me. Typos fixed, rebased, and pushed to the PR.

**Comment by ferd** [comment]
Looks good, got a +1, merging.

**Comment by choptastic** [comment]
Thanks for merging. I do also agree that the pdict leaves a bit of a sour taste in my mouth, at least the way I'm using it here. It gets the job done, but if there are other areas that could benefit from some faux memoization/cache hackery, perhaps there's a value in adding some kind of wrapper function to deal with that. Something like `rebar_utils:cache(Key, Fun)` where `Fun` is only evaluated if `Key` is not found, or whatever.

**Comment by tuncer** [comment]
I'm working on something like that, to be announced soon.

**Comment by choptastic** [comment]
That's great to hear! Thanks for the heads up.

**Pull request merged**
