### PR TITLE
Travis otp vsns

### PR DESCRIPTION
**Pull request by tuncer**
Try out some otp version changes in .travis.yml.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
If you are still interested in testing with old OTP Releases on Travis, we just deployed on-demand installations of OTP Releases not pre-installed. Some versions are now available for builds. (See https://github.com/travis-ci/travis-ci/issues/2757#issuecomment-119235879 for details.)

**Comment by tuncer** [comment]
@BanzaiMan, thanks, yes, we're still interested. Is there anything I have to do besides changing `otp_release` in `.travis.yml`?

**Comment by BanzaiMan** [comment]
@tuncer Besides setting `otp_release:` values, nothing is required. If the specified release is not pre-installed, it will be installed. (It may or may not work, depending on whether or not the archive is available; R14B01 is not, because the build process seg faults.)

**Comment by tuncer** [comment]
Are you sure the builds have been uploaded? This is what I get for R14B02, R14B, R13B04, R13B03:

```
The command "wget https://s3.amazonaws.com/travis-otp-releases
/ubuntu/$(lsb_release -rs)/erlang-R14B-x86_64.tar.bz2"
failed and exited with 8
```

**Comment by BanzaiMan** [comment]
ah. sorry. I need to change the file permissions.

**Comment by BanzaiMan** [comment]
Try again now.

**Comment by tuncer** [comment]
Okay, will do. What version of OTP did you use to build the rebar binary on travis-ci? For absolute compatibility, use R13B03 or R13B04. Also, do you know why the commented-out R14B01 entry is still used?

**Comment by tuncer** [comment]
Sorry, had an entry there, still. Removed now.

**Comment by tuncer** [comment]
Any idea why 17.2 is missing?

**Comment by tuncer** [comment]
@BanzaiMan can you switch the travis-ci kerl process to fetch git tags (releases) instead? That way we can access all OTP releases, including those which haven't been released as tarballs on http://erlang.org. That will solve the issue of missing OTP versions. For the missing 17.2 you would do this:

```
kerl build-install git https://github.com/erlang/otp.git OTP-17.2 17.2
```

**Comment by BanzaiMan** [comment]
@tuncer I'm not sure if that is a good idea. Building on the fly will add several minutes. As for 17.2, `kerl` does not recognize as a valid release name.

**Comment by ferd** [comment]
Yeah I'll have to agree. Building on the fly can easily take 15-20 minutes, and we just doubled the number of versions to test.

**Comment by BanzaiMan** [comment]
BTW, I've also built R13B02, 03 and 04. Those are available for on-demand installation.

**Comment by tuncer** [comment]
@BanzaiMan didn't you say on-demand builds will be cached the same way as the ones you built manually?

We can limit it to tarballs on erlang.org, but not all official releases are available that way. kerl could download a tarball for a git tag instead, if `git clone` is a concern, but someone has to modify kerl for that. Since git tags can be downloaded as tarballs, it seems logical to use that instead of detecting available releases with a regex applied to the erlang.org download folder listing.

To be clear, @ferd and @tsloughter suggested to test against all versions, so I completed the list. That said, I don't mind keeping the list short by, for example, testing only against each minor release (17.5.6.2, 18.0.2, etc.).

**Comment by BanzaiMan** [comment]
@tuncer I think there was a misunderstanding. The on-demand installation will pull the archive that https://github.com/travis-ci/travis-erlang-builder builds (which is a manual process) and uploads to our S3 bucket. My understanding is that `kerl build` pulls source from erlang.org when it builds.

Building from `git` via `kerl` doesn't sound like a good idea, if the resulting archive is not an official release, as this is meant for testing by Erlang users at large. If you need to test against specific tag on the git repo, then you are welcome to use `kerl build-install git …` as you indicated, but you are responsible for managing the runtimes.

**Comment by tuncer** [comment]
> @tuncer I think there was a misunderstanding. The on-demand installation will pull the archive that https://github.com/travis-ci/travis-erlang-builder builds (which is a manual process) and uploads to our S3 bucket. My understanding is that kerl build pulls source from erlang.org when it builds.

Okay.

> Building from git via kerl doesn't sound like a good idea, if the resulting archive is not an official release, as this is meant for testing by Erlang users at large. If you need to test against specific tag on the git repo, then you are welcome to use kerl build-install git … as you indicated, but you are responsible for managing the runtimes.

The OTP team does not make official releases with Windows installers for each minor release, and that's why some minor are missing on http://erlang.org. The tags (https://github.com/erlang/otp/releases) are official releases and the only way to access all releases. Just compare the official release tags to http://www.erlang.org/download.html. Strictly speaking, kerl is broken and does not support the new release versioning scheme (since 17.0). That's also why it misses many releases (including 17.2). Therefore, until kerl starts fetching tarballs from github (like https://github.com/erlang/otp/archive/OTP-18.0.2.tar.gz), the reasonable thing to do is building and archiving the official releases via `kerl build-install git...`.

Also, now that there's R13B03 on travis-ci, can you please rebuild the rebar binary (used by everybody on travis-ci) with that old release? That's important for the binary (and the included .beam files) to work with all otp releases.

**Comment by tuncer** [comment]
> @tuncer I think there was a misunderstanding. The on-demand installation will pull the archive that https://github.com/travis-ci/travis-erlang-builder builds (which is a manual process) and uploads to our S3 bucket. My understanding is that kerl build pulls source from erlang.org when it builds.

Okay.

> Building from git via kerl doesn't sound like a good idea, if the resulting archive is not an official release, as this is meant for testing by Erlang users at large. If you need to test against specific tag on the git repo, then you are welcome to use kerl build-install git … as you indicated, but you are responsible for managing the runtimes.

The OTP team does not make official releases with Windows installers for each minor release, and that's why some releases are missing on http://erlang.org. The tags (https://github.com/erlang/otp/releases) are official releases and the only way to access them all. Strictly speaking, kerl is broken and does not support the new versioning scheme (since 17.0). That's also why it misses many releases. Therefore, until kerl starts fetching tarballs from github (like https://github.com/erlang/otp/archive/OTP-18.0.2.tar.gz), the reasonable thing to do is building and archiving the official releases via `kerl build-install git...`.

Also, now that there's R13B03 on travis-ci, can you please rebuild the rebar binary (used by everybody on travis-ci) with that old release? That's important for the binary (and the included .beam files) to work with all otp releases.

**Comment by lrascao** [comment]
i've looked into this, apparently Travis doesn't use kerl to obtain OTP versions, it just downloads them from an S3 bucket, build #1 (https://travis-ci.org/lrascao/rebar/builds/108782313) shows this, maybe bug the Travis guys?

**Comment by tuncer** [comment]
@lrascao, yes, according to @BanzaiMan, prebuilt otp installations are stored on S3, but as kerl does not pick up all releases, we don't have access to those. First kerl needs to be fixed, or Travis-CI has to use a different mechanism to build OTP.

**Comment by tuncer** [comment]
See yrashk/kerl#111.

**Comment by tuncer** [comment]
@BanzaiMan, can you upgrade travis-ci's kerl now that kerl/kerl#122 has been merged? It will give you access to all releases by relying on git tags. This way, we will finally be able to use each and every official release, not just those that went through the special process which produced archives in erlang.org/download. Once that's updated, and you've prepared builds for all tags, all Erlang projects can use them in `.travis.yml`.

**Comment by BanzaiMan** [comment]
Currently, we do not rely on `kerl` to determine which versions of OTP Releases are available. Making changes to the mechanism is not trivial, and will take some time.

**Comment by tuncer** [comment]
@BanzaiMan, is it in any of the travis-ci open source projects, and can it be fixed sooner by an external contribution?

**Comment by tuncer** [comment]
@BanzaiMan, to be clear, you provisioned the available OTP releases with kerl, but you didn't use it to decide which ones should be. Is that correct?

**Comment by tuncer** [comment]
Closing due to silence from Travis-CI team.

**Pull request closed without merging**
