### PR TITLE
Start rebar's VM in -mode minimal

### PR DESCRIPTION
**Pull request by tuncer**
This reduces startup time by 100 to 200 milliseconds.

### CODE REVIEW

**Comment by tsloughter** [comment]
You don't get a network stack if you do that. Which is why the tests are failing.

**Comment by tuncer** [comment]
I know, distribution is missing. What's the right way to spin it up, or is this impossible after the vm has started?

**Comment by tsloughter** [comment]
I'm pretty sure it is impossible. I dug through the VM code to follow what minimal does at one point but don't remember the details.

**Comment by tuncer** [comment]
I'll close this then. Maybe we can come up with a custom boot file as an alternative.

**Comment by tuncer** [comment]
Here's the the alternative which reduces the overhead even more and doesn't suffer from the same limitation: #493.

**Pull request closed without merging**
