### PR TITLE
Add support for .tar.gz and .tar.bz2 dependencies

### PR DESCRIPTION
**Pull request by imrivera**
Hi!,

 I would find the support for .tar.gz and .tar.bz2 files very useful for my project. It just download and decompress the sources from the provided URL.

### CODE REVIEW

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
ping?

**Comment by ferd** [comment]
Yeah, still not merging without tests being in place. At some point if it never gets updated, I'll close this PR for being abandoned.

**Comment by tuncer** [comment]
I guess @ferd is right, and this can be closed abandoned.

**Pull request closed without merging**
