### PR TITLE
Automatically clean neotoma-generated erl files, regression test

### PR DESCRIPTION
**Pull request by lrascao**
Integration regression test that checks for correct generation of .erl files from .peg ones and that they are cleaned up.
Should be merged only when #526 is also.

### CODE REVIEW

**Comment by tuncer** [comment]
The new test seems to fail.

**Comment by lrascao** [comment]
the new test relies on the clean capabilities introduced in #526, maybe the commits should be bundled together in a single PR?

**Comment by tuncer** [comment]
Right, either you cherry-pick d2ad8cd from #526, or 4b78827 is picked into #526.

**Comment by lrascao** [comment]
@macintux @tuncer, cherry-picked 4b78827 from #526

**Comment by tuncer** [comment]
Thanks, let's merge this as the completed #526 then.

**Comment by tuncer** [comment]
cc @ferd @tsloughter

**Comment by tuncer** [comment]
And we need to append John Daily in THANKS as well.

**Comment by macintux** [comment]
Sorry for missing the original testing merge request in #526, was traveling; is there anything I need to do?

Thanks for jumping on this.

**Comment by lrascao** [comment]
@macintux Could you please append your name to the THANKS file in commit 245af53ccfd10680516dd6f3801afed27ab588c9? i'll re-pick it

**Comment by macintux** [comment]
I couldn't find that commit; I edited/force pushed the last commit on my branch, so the THANKS change appears in #526. Let me know if I need to do something different

**Comment by lrascao** [comment]
@macintux Could you please rebase cleanly onto master? i'm having trouble picking 1ed041bd due to a conflict in THANKS file

**Comment by lrascao** [comment]
ping?

**Comment by lrascao** [comment]
Rebased branch and cherry-picked @macintux's 1ed041bdede45bfb5c60086e9ae6fd887d090ce1 commit, ready to merge

**Comment by tuncer** [comment]
+1

**Pull request merged**
