### PR TITLE
Revert "Delete obsolete file"

### PR DESCRIPTION
**Pull request by ferd**
Reverts rebar/rebar#440

This somehow made tests break in master for R14B03

### CODE REVIEW

**Comment by ferd** [comment]
@tuncer any idea? Maybe it was a travis issue?

**Comment by tuncer** [comment]
Where's the log? I cannot imagine how that patch would break anything.

**Comment by tuncer** [comment]
The status picture says "build error", but the build is all green. See https://travis-ci.org/rebar/rebar/builds/47933202.

**Comment by ferd** [comment]
Ah, they must have re-run it until it worked. Disregard this.

**Comment by tuncer** [comment]
The image is still saying "build error", though.

**Comment by ferd** [comment]
As long as the build isn't actually broken it's not too bad. Just appearances.

**Comment by tuncer** [comment]
It was a travis-ci glitch.

**Pull request closed without merging**
