### PR TITLE
added 'shell' command to bash-completion

### PR DESCRIPTION
**Pull request by yannayl**
updated the bash shell auto-completion to complete the 'rebar shell' command

### CODE REVIEW

**Comment by tuncer** [comment]
Thanks.

Please:
1. Change the commit message according to [CONTRIBUTING#writing-commit-messages](https://github.com/rebar/rebar/blob/master/CONTRIBUTING.md#writing-commit-messages): `added` -> `Add`
2. Append your name in `THANKS`

Also, if you want to, you can add the missing entry in the zsh completion script as well.

**Comment by tuncer** [comment]
Thanks.

Please:
1. Change the commit message according to [CONTRIBUTING#writing-commit-messages](https://github.com/rebar/rebar/blob/master/CONTRIBUTING.md#writing-commit-messages): `added` -> `Add`, `updated` -> `Update`, and terminate the description (not the summary) with a period.
2. Append your name in `THANKS`

Also, if you want to, you can add the missing entry in the zsh completion script as well.

**Comment by yannayl** [comment]
Welcome.

1. Done (commit amend).
2. Will be done when I contribute something a little bit more significant :-)

Sorry, but I am not zsh user and don't understand the syntax of the completion file (I tried, but don't have time to study it right now).

**Comment by tuncer** [comment]
Thanks, but since the rewritten commit description just duplicates the summary, you can omit that or restore the previous text. As there's no explanation required, I'd say omit the description.

Here's the zsh patch: #453.

**Comment by yannayl** [comment]
ok.

I merged your patch into mine and committed again.

**Comment by tuncer** [comment]
+1

**Pull request merged**
