### PR TITLE
Add support for Windows integration testing

### PR DESCRIPTION
**Pull request by lrascao**
Use retest feature/rebar-windows-ci branch that adds Windows
tests support, test setup callback and additional touch command.
This is temporary while waiting on a final merge to retest master.
For all tests copy rebar and rebar.cmd using retest setup callback.
Port OS specific commands used in tests to Erlang
(eg. touch, rm, cp, stat..).

rebar_ct: do away with grep command line invocation (which doesn't
exist in Windows) and use instead plain Erlang parsing.

### CODE REVIEW

**Comment by tuncer** [comment]
Excellent, but don't you think that, given Erlang's flat namespace, `utils` is too likely to clash?

**Comment by lrascao** [comment]
good point, i'll rename it to `inttest_utils`

**Comment by lrascao** [comment]
All tests are now passing on Appveyor, waiting on @dizzyd to merge retest PR's dizzyd/retest#16, dizzyd/retest#22, dizzyd/retest#21 (these last two are nice to haves) to master before ready to merge this branch.

**Comment by lrascao** [comment]
The above mentioned PR's have been merge to retest master and tagged 1.1.0. 
On my end this is ready to merge to master, if everybody is ok with the changes i'll proceed with the merge
cc @ferd @tuncer

**Comment by ferd** [comment]
+1, move ahead when ready.

**Comment by tuncer** [comment]
+1

**Pull request merged**
