### PR TITLE
Add pr2relnotes tool to generate release notes

### PR DESCRIPTION
**Pull request by jaredmorrow**

### CODE REVIEW

**Comment by tuncer** [comment]
Thanks @jaredmorrow. What's the license of the script?

**Comment by jaredmorrow** [comment]
Oh, whatever rebar is under, MIT, BSD, Creative Commons, I don't mind.

**Comment by tuncer** [comment]
Without an explicit license, it'll be Apache 2 licensed then. All source files in rebar are explicitly MIT (Expat) licensed.

I'd prefer an explicit license prologue in the script, if anybody wants to reuse it another project, but you'd have to submit such a patch, so it's up to you.

**Comment by jaredmorrow** [comment]
I will a bit later, thanks.

**Pull request merged**
