### PR TITLE
Add integration tests for simplenode.runner

### PR DESCRIPTION
**Pull request by evnu**
This changeset adds integration test for `priv/templates/simplenode.runner`. It tests the script against an example release and also tries to perform a release upgrade.

Tested on ArchLinux and Apple Mac OS X 10.10.4..

### CODE REVIEW

**Comment by evnu** [comment]
The timeouts in the patchset are not very large (1s mostly). This could be a problem for travis.

**Comment by lrascao** [comment]
Maybe we should have a VW component that increases these timeouts for Travis builds

**Comment by evnu** [comment]
For OTP versions < 17, the testsetup is faulty. I will fix that now.

**Comment by evnu** [comment]
I extended the test suite to also cover OTP versions before R15B01. Running the tests succeeds locally, but it seems that I am still having problems with travis.

**Comment by evnu** [comment]
I fixed the problems with older Erlang releases (https://github.com/rebar/rebar/commit/26343299ec7e2c77757651590d7548832adbf4f0). Unfortunately, I did not find a way to fix some test cases in `basic_rt.erl` for Travis. I think I am missing something about how to use the `-heart` option with Travis. Also, `start_boot` does not start a node properly, but I could not extract any log files or error messages for that.

**Comment by evnu** [comment]
I fixed the remaining problems with travis in https://github.com/rebar/rebar/commit/ca30203f7b0579ef0720268a7c0a250f2b4ec789. I removed certain test cases (`start_boot`, `restart`, `reboot`), as I could not get them to run reliably with travis.

**Comment by evnu** [comment]
With https://github.com/evnu/rebar/commit/2f7880d8416716af4c74e361ee1c66ecc85012a5, I removed the trailing . from the first commit summary as asked for by @tuncer  in #550.

**Comment by tuncer** [comment]
Bump?

**Pull request closed without merging**
