### PR TITLE
Add erl_first_files in eunit_first_files and qc_first_files

### PR DESCRIPTION
**Pull request by platinumthinker**
Fix compile order for tests

### CODE REVIEW

**Comment by tuncer** [comment]
This looks reasonable and needs a test before merge, but why did you restrict it to "qc" and "eunit"?

**Comment by platinumthinker** [comment]
I saw this behaviour in tests. I add erl_first_files in all first_files..
I think about general first_files instead of separate.

**Comment by tuncer** [comment]
You can skip the list_to_atom call and just use `erl_first_files` in the new version.

Regarding tests, it makes sense to check the new behavior explicitly in a test, maybe as follows:

1. eunit with first rebar.config, which does not have erl_first_files, and expect build failure
2. clean
3. eunit with second rebar.config, which has erl_first_files, and expect build+eunit success

**Comment by tuncer** [comment]
ping?

**Comment by platinumthinker** [comment]
I have been on vacation. I am back now and continue to work on this.

**Comment by platinumthinker** [comment]
ping?

**Comment by tuncer** [comment]
1. The unneeded `list_to_atom("erl_first_files")` is still there.
2. You're not testing the case where the test fails without erl_first_files. Thinking about it, I don't think you can test, because erlc_compiler detects a parse_transform compiler directive and automatically adds it as a dependency. I'm not sure how to test the failure case.

**Comment by tuncer** [comment]
1. The unneeded `list_to_atom("erl_first_files")` is still there.
2. You're not testing the case where the test fails without erl_first_files. However, I don't think you can test, because erlc_compiler detects a parse_transform compiler directive and automatically adds it as a dependency. I'm not sure how to test the failure case.

**Comment by tuncer** [comment]
1. The unneeded `list_to_atom("erl_first_files")` is still there.
2. You're not testing the case where the test fails without erl_first_files. However, I don't think you can test that, because erlc_compiler detects a parse_transform compiler directive and automatically adds it as a dependency. I'm not sure how to test the failure case.

**Comment by platinumthinker** [comment]
I agree with you on second position. First thing is fixed.

**Comment by tuncer** [comment]
You should just use the atom `erl_first_files`. No variable needed.

**Comment by tuncer** [comment]
You should simply use the atom `erl_first_files`. No variable needed.

**Comment by tuncer** [comment]
There's no need to quote erl_first_files.

**Comment by platinumthinker** [comment]
This true, but not mandatory.
Example in this file:
```41: -type erlc_info_v() :: {digraph:vertex(), term()} | 'false'.```
```210:                     {platform_define, "R13", 'old_inets'}]},```

**Comment by tuncer** [comment]
Yes, but (1) in type specs it's customary to quote atoms and (2) we don't quote atoms in any other rebar_config call, which makes this case break the consistency for no reason.

**Comment by platinumthinker** [comment]
okay

**Comment by tuncer** [comment]
Thanks. +1, once you've squashed the fixups into the original commit.

**Comment by platinumthinker** [comment]
Squashed is done

**Pull request merged**
