### PR TITLE
Add the latest OTP 18 version to the Travis build

### PR DESCRIPTION
**Pull request by lrascao**

### CODE REVIEW

**Comment by tuncer** [comment]
See also #295. Once kerl is fixed, travis-ci will be able to make all otp releases available.

**Comment by lrascao** [comment]
Cool, hadn't noticed that one, do you want to try and put #295 through Travis again and see how it behaves?

**Comment by tuncer** [comment]
Sure, but not before next week. In the meantime, feel free to patch kerl :).

**Comment by tuncer** [comment]
To be clear, the missing otp versions won't magically appear. kerl needs to be fixed to build from git tag tarballs, not just what's inside erlang.org/download.

**Comment by tuncer** [comment]
Updated #295.

**Pull request merged**
