### PR TITLE
Add Windows continuous integration through AppVeyor

### PR DESCRIPTION
**Pull request by lrascao**
Windows builds/tests activated on master branch only, badge added to README

### CODE REVIEW

**Comment by tuncer** [comment]
+1

**Comment by lrascao** [comment]
Travis tests are failing due to timeouts, is this a known issue?

**Comment by tuncer** [comment]
This particular timeout isn't a regular issue and it happened only for one OTP release. I'd expect all tests to succeed if you force a retest.

**Comment by lrascao** [comment]
Indeed they did

**Pull request merged**
