### PR TITLE
port_compiler: auto-select C++ specific link template

### PR DESCRIPTION
**Pull request by tuncer**
Even though "$CC foo.o -lstdc++ -o foo.so" works if foo.o was built with
$CXX, depending on the platform and toolchain and C++ standard used, it
may not. In order to ensure this works reliably, we introduce
EXE_LINK_CXX_TEMPLATE and DRV_LINK_CXX_TEMPLATE and auto-select if the
port spec being built consists of at least one C++ source.

### CODE REVIEW

**Comment by tuncer** [comment]
@laverite, can you verify this fixes https://github.com/tuncer/re2/issues/15?

**Comment by tuncer** [comment]
Alternatively, we could introduce `$LINKER` and used that instead of `$CC` in `$EXE_LINK_TEMPLATE` and `$DRV_LINK_TEMPLATE`.

**Comment by laverite** [comment]
@tuncer thank you, yeah that works for me when I use rebar.  but i'm using rebar3 :D.

**Comment by tuncer** [comment]
@lrascao, can you please review?

**Comment by lrascao** [comment]
@tuncer looks good, merging

**Pull request merged**
