### PR TITLE
Run update-deps hooks again

### PR DESCRIPTION
**Pull request by Vagabond**
Fix regression caused by making update-deps actually work.

### CODE REVIEW

**Comment by tuncer** [comment]
So, what do we do about this? As I said earlier, given a clear NOTE/TODO comment, it's okay to merge, assuming this fixes the regression.

**Comment by ferd** [comment]
I frankly have no idea. I don't understand this code base, don't understand the implications, never know what may break or not. I'm fine with merging it and reversing if it breaks more stuff, though.

**Comment by tuncer** [comment]
So, how about merging this to master after the next release, and see if anything breaks?

**Comment by ferd** [comment]
Sure, that sounds like a plan. The current release is still blocked on getting the proper protobuffs configs fixed, though.

**Comment by tuncer** [comment]
I think it's safe to say this can be closed (together with #561).

**Pull request closed without merging**
