### PR TITLE
Fix otp_release() when OTP_VERSION file not exists

### LINKED ISSUE #350: Rebar 2.5.1 crashes with a reltool-generated release on Erlang 17+
It seems that with a reltool generated release, rebar will crash when checking the OTP version due to the version change.  Version 2.5.0 works okay (the commit that breaks it is this: https://github.com/rebar/rebar/commit/873d236ce9b4b88d46c4bb1c6868df70363e8a57)

It crashes on this line: https://github.com/rebar/rebar/blob/master/src/rebar_utils.erl#L391 because the generated release doesn't include the OTP_VERSION file in the releases directory by default.

I'm unsure if this is something that should be fixed within rebar or if it's an oversight by the otp team with the release of Erlang 17, but I thought I'd mention it here.

The full error is as follows:
```erlang
Uncaught error in rebar_core: {'EXIT',
                               {{badmatch,{error,enoent}},
                                [{rebar_utils,otp_release1,1,
                                  [{file,"src/rebar_utils.erl"},{line,391}]},
                                 {rebar_utils,get_arch,0,
                                  [{file,"src/rebar_utils.erl"},{line,92}]},
                                 {rebar_port_compiler,default_env,0,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,574}]},
                                 {rebar_port_compiler,setup_env,2,
                                  [{file,"src/rebar_port_compiler.erl"},
                                   {line,181}]},
                                 {rebar_core,'-setup_envs/2-fun-0-',2,
                                  [{file,"src/rebar_core.erl"},{line,522}]},
                                 {lists,foldl,3,
                                  [{file,"lists.erl"},{line,1261}]},
                                 {rebar_core,maybe_execute,8,
                                  [{file,"src/rebar_core.erl"},{line,293}]},
                                 {rebar_core,process_dir1,7,
                                  [{file,"src/rebar_core.erl"},{line,258}]}]}}
make[3]: *** [get-deps] Error 1
```

I haven't spent any time looking at this too closely to try and fix it yet, I just reverted to 2.5.0 because it works well enough.

Thanks!

### PR DESCRIPTION
**Pull request by choptastic**
If the OTP_VERSION file doesn't exist at all for (in a reltool-generated-release's for OTP > 17 binaries) we attempt to infer the OTP version from included applications. In this commit, just the erts application is checked but if the erts version is not changed, we could check other applications.

I realize that this PR does not include any tests, I'm more just spitballing here to see if this level of fallback is acceptable. If this is acceptable, then I can spend the extra time to add some tests, but this is more of a conversation stimulator - unless, you actually like this as is, then by all means, merge away!

Alternatively, (and from conversations with @tuncer), a much simpler approach, though one that would sacrifice version granularity, would be to simply return a string like "17.x" if the OTP_VERSION file is not found.

Thoughts?

Fixes #350.

### CODE REVIEW

**Comment by tuncer** [comment]
Isn't it good enough to just use the result of
erlang:system_info(otp_release) and print the no-OTP_VERSION-file warning,
stating the version string we have is probably not specific enough? I don't
like having to maintain a table of erts versions.

**Comment by tuncer** [comment]
Isn't it good enough to just use the result of erlang:system_info(otp_release) and print the no-OTP_VERSION-file warning, stating the version string we have is probably not specific enough? I don't like having to maintain a table of erts versions. Alternatively, as I suggested in #350, we could copy OTP_VERSION into the generated release.

**Comment by choptastic** [comment]
> I don't like having to maintain a table of erts versions.

It also leaves a bit of a sour taste in my mouth, and I do agree with that. It's rather putzy, but gives us some granularity.

As for copying the OTP_VERSION file, I'd be open to that, but for existing releases, that obviously doesn't help. The above would be *okay* in that situation, but not great. I'd also at least like to have it generate a warning about the missing file, and rely upon the erlang:system_info(otp_release) in that case.

Truthfully, as it is right now, I just use 2.5.0 because it just uses erlang:system_info(otp_release)  and doesn't look for the OTP_VERSION file - so that extremely naive version  ("17") is enough for my immediate needs. This was more of a "why not?" kind of a PR - since as I was making my simple fix, I thought, "Hey, this seems like it could be helpful and it's relatively easy to do, even if it has to be updated for every release").

**Comment by ferd** [comment]
Yeah Rebar3 went with just using the major version if the OTP file isn't there and I can't remember if we warn. I forgot to port this back to this version of rebar.

**Comment by choptastic** [comment]
I'll put together a simpler PR for this tonight that doesn't try to infer
the minor version numbers.

**Pull request closed without merging**
