### PR TITLE
Treat port env vars as expandable only if they self reference

### PR DESCRIPTION
**Pull request by lrascao**
Addresses #348 
Provide additional port test case.
Also, update newest OS X versions build flags.

### CODE REVIEW

**Comment by tuncer** [comment]
+1. This also resolves #182.

**Comment by lrascao** [comment]
thanks, i'll look into it

**Comment by lrascao** [comment]
@jflatow do you have a Makefile example with the issue you described? i'm having a bit of trouble replicating it

**Comment by jflatow** [comment]
Sure, for example create a simple app called bar, with rebar.config:

```
{erl_opts, [debug_info, warnings_as_errors, warn_export_all]}.
{deps,
 [{'discodb', ".*",
   {git, "https://github.com/jflatow/discodb.git", "master"}, [raw]}]}.
{pre_hooks,
 [{compile, "make -C $REBAR_DEPS_DIR/discodb erlang"}]}.
```

And for completeness, src/bar.app.src:
```
{application, bar,
 [{vsn, []},
  {mod, {agency, []}},
  {applications, [kernel, stdlib]}]}.
```

**Comment by lrascao** [comment]
I tried out your example but still can't reproduce it, can you paste the error you're getting and the output of `rebar --version` you're using? thanks!

**Comment by jflatow** [comment]
On anything from b816c69e343c8fd757c59fe8703eeda597f4da0a...9281b848f563e4928b565fab57b610c7368c0be6 I get an error:

```
==> erlang (compile)
Compiling c_src/ddb.c
c_src/ddb.c:9:10: fatal error: 'discodb.h' file not found
#include <discodb.h>
         ^
1 error generated.
```

On 022afd4b08fe024520849e50fd2bd03294fe210a or earlier, it works.

**Comment by lrascao** [comment]
got it, i see it now, i was using the 2.6.1 rebar that's in the path, that one doesn't have the regression

**Comment by lrascao** [comment]
c43f2e55 revert fixes the regression

**Pull request merged**
