### PR TITLE
compiler respects 'keep_going' flag

### PR DESCRIPTION
**Pull request by vladdu**
I am creating this PR as a base for further discussion.

I found that this change works fine for me, but I don't know if the fact that the worker pid is not removed has any bad effects.

### CODE REVIEW

**Comment by tuncer** [comment]
ping?

**Comment by ferd** [comment]
I'd like this to be rebased to merge it. If we don't hear back, then I'll do it myself, but these are busy days and if I can avoid rebasing this myself, I'd like to.

**Comment by vladdu** [comment]
I'll rebase it. 

Is it okay to keep the test as they are, or should they be rewritten as retest tests?

**Comment by tuncer** [comment]
It'd be nice to have it as a retest test, but it's fine as is once you fix the formatting issues pointed out by @ferd.

**Comment by ferd** [comment]
I'm guessing the retest suite would provide a better integration, but if the tests run along with everything else *and* represent actual use cases, I personally do not mind much on this. @tuncer ?

**Comment by tuncer** [comment]
See earlier https://github.com/rebar/rebar/pull/354#issuecomment-88897719. It'd be nice as retest tests, but it's fine as is.

**Comment by vladdu** [comment]
I hope the formatting is okay now.

**Comment by ferd** [comment]
It looks good to me. @tuncer any last comment before I merge this?

**Comment by tuncer** [comment]
You can merge it.

**Pull request merged**
