### PR TITLE
Automatically clean neotoma-generated erl files

### PR DESCRIPTION
**Pull request by macintux**
Remove `.erl` files on clean that appear to have been converted from `.peg`.

### CODE REVIEW

**Comment by lrascao** [comment]
@macintux Would you consider cherry picking the commit from #532 into this PR? It consists of a regression test for the feature you have introduced

**Comment by tuncer** [comment]
What's the status? Is one of the pull requests ready to merge?

**Comment by lrascao** [comment]
I suppose we can merge this one right away and afterwards merge #532 which is the regression test (after i clean it up), ideally both commits should be in the same PR but this is one way of moving forward.

**Comment by tuncer** [comment]
ping?

**Comment by lrascao** [comment]
Closing in favor of #532 which contains this fix plus regression tests

**Pull request closed without merging**
