### PR TITLE
Fix cdb processing when a file is skipped

### PR DESCRIPTION
**Pull request by tuncer**
This fixes a bug introduced in the new code in 2.6.3. We should release 2.6.4.

### CODE REVIEW

**Comment by lrascao** [comment]
Are there no regression tests for this?

**Comment by tuncer** [comment]
None that would have caught this. I've noticed this during the backport of changes to blt/port_compiler.

**Comment by tuncer** [comment]
I'll extract that into a variable for good measure.

**Comment by tuncer** [comment]
Investigating a build failure in https://github.com/travelping/gen_socket.

**Comment by tuncer** [comment]
Fixed handling of multiple specs.

**Pull request merged**
